[build]
  base    = "frontend"
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"

# Supabase Functions
[functions]
  directory = "supabase/functions"

# Redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"